{{- $adminUser := .Values.secrets.adminUser | default "admin" | b64enc }}
{{- $adminPassword := .Values.secrets.adminPassword | default (randAlpha 20) | b64enc }}
{{- $dbPassword := .Values.secrets.dbPassword | default (randAlpha 20) | b64enc }}
apiVersion: v1
kind: Secret
metadata:
  name: keycloak-init-secrets
type: Opaque
data:
  username: {{ $adminUser }}
  password: {{ $dbPassword }}
  admin-password: {{ $adminPassword }}
